apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - platform-config.yaml
  - network/default-deny-ingress-opt-in.yaml
  - kafka/zookeeper.yaml
  - kafka/kafka.yaml
  - kafka/kafka-ui.yaml
